version: "3.1"

services:
  mongodb:
    image: mongo
    restart: always
    volumes: 
      - ./database-persistent:/data/db
    ports: 
      - '27017:27017'
    environment: 
      MONGO_INITDB_DATABASE: 'userData'

  node:
    image: rest-desafio:latest
    restart: always
    ports: 
      - '5000:5000'
    environment: 
      SECRET_KEY: "HDSiuheb98yDOSIgd¨72389GYUdgaksgyu"

volumes:
  myapp: